/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MIPTDOUBLEGAUSSIAN2
#define MIPTDOUBLEGAUSSIAN2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MiptDoubleGaussian2 : public RooAbsPdf {
public:
  MiptDoubleGaussian2() {} ; 
  MiptDoubleGaussian2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _frac2,
	      RooAbsReal& _mpeak,
	      RooAbsReal& _mth,
	      RooAbsReal& _w1,
	      RooAbsReal& _w2,
	      RooAbsReal& _beta);
  MiptDoubleGaussian2(const MiptDoubleGaussian2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MiptDoubleGaussian2(*this,newname); }
  inline virtual ~MiptDoubleGaussian2() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy frac2 ;
  RooRealProxy mpeak ;
  RooRealProxy mth ;
  RooRealProxy w1 ;
  RooRealProxy w2 ;
  RooRealProxy beta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MiptDoubleGaussian2,1) // Your description goes here...
};
 
#endif
