/*
* Author: Jingqing Zhang, jingqing@cern.ch
* Functions for the fit package 
* with/without interference between resonances (and SPS)
*/
/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYRELBWSQUARE
#define MYRELBWSQUARE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyRelBWSquare : public RooAbsPdf {
public:
  MyRelBWSquare() {} ; 
  MyRelBWSquare(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mass1,
	      RooAbsReal& _width1,
	      RooAbsReal& _L1,
	      RooAbsReal& _d1,
	      RooAbsReal& _coef1,
	      RooAbsReal& _phi1);
  MyRelBWSquare(const MyRelBWSquare& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyRelBWSquare(*this,newname); }
  inline virtual ~MyRelBWSquare() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass1 ;
  RooRealProxy width1 ;
  RooRealProxy L1 ;
  RooRealProxy d1 ;
  RooRealProxy coef1 ;
  RooRealProxy phi1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyRelBWSquare,1) // Your description goes here...
};
 
#endif
