/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYEFFFCN
#define MYEFFFCN

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyEffFcn : public RooAbsReal {
public:
  MyEffFcn() {} ; 
  MyEffFcn(const char *name, const char *title,
	      RooAbsReal& _x);
  MyEffFcn(const MyEffFcn& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyEffFcn(*this,newname); }
  inline virtual ~MyEffFcn() { }

protected:

  RooRealProxy x ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyEffFcn,1) // Your description goes here...
};
 
#endif
