/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYRELBW1RELBW2INTERFFCN
#define MYRELBW1RELBW2INTERFFCN

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyRelBW1RelBW2InterfFcn : public RooAbsReal {
public:
  MyRelBW1RelBW2InterfFcn() {} ; 
  MyRelBW1RelBW2InterfFcn(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mass1,
	      RooAbsReal& _width1,
	      RooAbsReal& _L1,
	      RooAbsReal& _d1,
	      RooAbsReal& _coef1,
	      RooAbsReal& _phi1,
	      RooAbsReal& _mass2,
	      RooAbsReal& _width2,
	      RooAbsReal& _L2,
	      RooAbsReal& _d2,
	      RooAbsReal& _coef2,
	      RooAbsReal& _phi2);
  MyRelBW1RelBW2InterfFcn(const MyRelBW1RelBW2InterfFcn& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyRelBW1RelBW2InterfFcn(*this,newname); }
  inline virtual ~MyRelBW1RelBW2InterfFcn() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass1 ;
  RooRealProxy width1 ;
  RooRealProxy L1 ;
  RooRealProxy d1 ;
  RooRealProxy coef1 ;
  RooRealProxy phi1 ;
  RooRealProxy mass2 ;
  RooRealProxy width2 ;
  RooRealProxy L2 ;
  RooRealProxy d2 ;
  RooRealProxy coef2 ;
  RooRealProxy phi2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyRelBW1RelBW2InterfFcn,1) // Your description goes here...
};
 
#endif
