/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYSPSDPSPDF
#define MYSPSDPSPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MySPSDPSPdf : public RooAbsPdf {
public:
  MySPSDPSPdf() {} ; 
  MySPSDPSPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a,
	      RooAbsReal& _b,
	      RooAbsReal& _p2,
	      RooAbsReal& _p1,
	      RooAbsReal& _p0);
  MySPSDPSPdf(const MySPSDPSPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MySPSDPSPdf(*this,newname); }
  inline virtual ~MySPSDPSPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  RooRealProxy p2 ;
  RooRealProxy p1 ;
  RooRealProxy p0 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MySPSDPSPdf,1) // Your description goes here...
};
 
#endif
